name: Reminder to Renew Self-signed Test Certificate
on:
  schedule:
    # 04:05 on Monday in January and July
    - cron: 5 4 * 1,7 1
jobs:
  create_issue:
    name: Create reminder
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Renew self-signed test certificate
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Renew self-signed test certificate
          body: |
            The self-signed test certificate for ReactTestApp on Windows is about to expire.

            1. Run `.\scripts\Renew-SelfSignedCertificate.ps1` in PowerShell
            2. Run `yarn install-windows-test-app` inside `example`
            3. Open the project and verify that it uses the new certificate
            4. Verify that the test app builds and runs
            5. Commit `ReactTestApp.vcxproj` and `ReactTestApp_TemporaryKey.pfx`
            6. Submit a PR

            For a concrete example, have a look at \#385.

            For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
          labels: "platform: Windows"
          assignees: tido64
